<%@ page isELIgnored="true" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<jsp:include page="questions/q0.jsp" />
<jsp:include page="questions/q1.jsp" />
<jsp:include page="questions/q2.jsp" />
<jsp:include page="questions/q3.jsp" />
<jsp:include page="questions/q4.jsp" />
<jsp:include page="questions/q5.jsp" />
<jsp:include page="questions/q6.jsp" />
<jsp:include page="questions/q7.jsp" />
<jsp:include page="questions/q8.jsp" />
<jsp:include page="questions/q9.jsp" />
<jsp:include page="questions/q10.jsp" />
<jsp:include page="questions/q11.jsp" />
<jsp:include page="questions/q12.jsp" />
<jsp:include page="questions/q13.jsp" />
<jsp:include page="questions/q14.jsp" />
<jsp:include page="questions/q15.jsp" />
<jsp:include page="questions/q16.jsp" />
<jsp:include page="questions/q17.jsp" />
<jsp:include page="questions/q18.jsp" />
<jsp:include page="questions/q19.jsp" />
<jsp:include page="questions/q20.jsp" />
<jsp:include page="questions/q21.jsp" />
